
model:
    optimizer: 'Adam'
    scheduler: 'CosAn'
    loss: 'L2'    
    augmentation: False
    image_grad: False
    kernel_K: False
    pure_atlas_bulding: True
    reduced_dim: 16
    pretrain_epoch: 20

solver:
    lr: 0.005
    atlas_lr: 0.01
    epochs: 200
    batch_size: 50
    weight_decay: 0.0001
    pre_train: 20
    Euler_steps: 12
    Alpha: 5
    Gamma: 0.5
    Lpow: 2 
    Sigma: 0.02
