
model:
    optimizer: 'Adam'
    scheduler: 'CosAn'
    loss: 'L2'    
    augmentation: False
    image_grad: False
    kernel_K: False
    pure_atlas_bulding: True
    reduced_dim: 16
    pretrain_epoch: 0

solver:
    lr: 0.001
    atlas_lr: 0.005
    epochs: 3
    batch_size: 16
    weight_decay: 0.0001
    pre_train: 0
    Euler_steps: 10
    Alpha: 5
    Gamma: 0.5
    Lpow: 2 
    Sigma: 0.02
